-- DEPRECATED & UNIFIED INTO MYSQL (wapi_weaver)
-- Esta aplicação utiliza exclusivamente o MySQL 8.0 através do script oficial scripts/ensure-schema.js.
-- Qualquer tabela de CRM, contatos, bot, DS agente, licenças e webhooks é gerenciada no MySQL.
