// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      let targetProvider: any = provider;
      if (provider === "lovable") {
        targetProvider = "google";
      } else if (provider === "microsoft") {
        targetProvider = "azure";
      }

      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: targetProvider,
        options: {
          redirectTo: opts?.redirect_uri || (typeof window !== "undefined" ? window.location.origin : undefined),
          queryParams: opts?.extraParams,
        },
      });

      if (error) {
        return { error, redirected: false };
      }

      if (typeof window !== "undefined" && data?.url) {
        window.location.assign(data.url);
        return { redirected: true };
      }

      return { redirected: false };
    },
  },
};
