/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as AppWebhookEventsRouteImport } from './routes/_app/webhook-events'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppListsRouteImport } from './routes/_app/lists'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns.index'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageRemoveRouteImport } from './routes/api/storage/remove'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicMakeAdminRouteImport } from './routes/api/public/make-admin'
import { Route as ApiAuthUpdateRouteImport } from './routes/api/auth/update'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminSchemaDumpRouteImport } from './routes/api/admin/schema-dump'
import { Route as AppCampaignsIdRouteImport } from './routes/_app/campaigns.$id'
import { Route as ApiPublicCronProcessQueueRouteImport } from './routes/api/public/cron/process-queue'
import { Route as ApiPublicContactsIngestRouteImport } from './routes/api/public/contacts/ingest'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhookEventsRoute = AppWebhookEventsRouteImport.update({
  id: '/webhook-events',
  path: '/webhook-events',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRemoveRoute = ApiStorageRemoveRouteImport.update({
  id: '/api/storage/remove',
  path: '/api/storage/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMakeAdminRoute = ApiPublicMakeAdminRouteImport.update({
  id: '/api/public/make-admin',
  path: '/api/public/make-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpdateRoute = ApiAuthUpdateRouteImport.update({
  id: '/api/auth/update',
  path: '/api/auth/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSchemaDumpRoute = ApiAdminSchemaDumpRouteImport.update({
  id: '/api/admin/schema-dump',
  path: '/api/admin/schema-dump',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCronProcessQueueRoute =
  ApiPublicCronProcessQueueRouteImport.update({
    id: '/api/public/cron/process-queue',
    path: '/api/public/cron/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactsIngestRoute = ApiPublicContactsIngestRouteImport.update({
  id: '/api/public/contacts/ingest',
  path: '/api/public/contacts/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/chat': typeof AppChatRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lists': typeof AppListsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/webhook-events': typeof AppWebhookEventsRoute
  '/api/query': typeof ApiQueryRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/api/admin/schema-dump': typeof ApiAdminSchemaDumpRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/update': typeof ApiAuthUpdateRoute
  '/api/public/make-admin': typeof ApiPublicMakeAdminRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/remove': typeof ApiStorageRemoveRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/api/public/contacts/ingest': typeof ApiPublicContactsIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/chat': typeof AppChatRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lists': typeof AppListsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/webhook-events': typeof AppWebhookEventsRoute
  '/api/query': typeof ApiQueryRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/api/admin/schema-dump': typeof ApiAdminSchemaDumpRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/update': typeof ApiAuthUpdateRoute
  '/api/public/make-admin': typeof ApiPublicMakeAdminRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/remove': typeof ApiStorageRemoveRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/api/public/contacts/ingest': typeof ApiPublicContactsIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lists': typeof AppListsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/webhook-events': typeof AppWebhookEventsRoute
  '/api/query': typeof ApiQueryRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/api/admin/schema-dump': typeof ApiAdminSchemaDumpRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/update': typeof ApiAuthUpdateRoute
  '/api/public/make-admin': typeof ApiPublicMakeAdminRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/remove': typeof ApiStorageRemoveRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/api/public/contacts/ingest': typeof ApiPublicContactsIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/audit'
    | '/billing'
    | '/chat'
    | '/contacts'
    | '/dashboard'
    | '/lists'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/users'
    | '/webhook-events'
    | '/api/query'
    | '/campaigns/$id'
    | '/api/admin/schema-dump'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/update'
    | '/api/public/make-admin'
    | '/api/public/whatsapp-webhook'
    | '/api/storage/file'
    | '/api/storage/remove'
    | '/api/storage/upload'
    | '/campaigns/'
    | '/api/public/contacts/ingest'
    | '/api/public/cron/process-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/audit'
    | '/billing'
    | '/chat'
    | '/contacts'
    | '/dashboard'
    | '/lists'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/users'
    | '/webhook-events'
    | '/api/query'
    | '/campaigns/$id'
    | '/api/admin/schema-dump'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/update'
    | '/api/public/make-admin'
    | '/api/public/whatsapp-webhook'
    | '/api/storage/file'
    | '/api/storage/remove'
    | '/api/storage/upload'
    | '/campaigns'
    | '/api/public/contacts/ingest'
    | '/api/public/cron/process-queue'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/chat'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/lists'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/users'
    | '/_app/webhook-events'
    | '/api/query'
    | '/_app/campaigns/$id'
    | '/api/admin/schema-dump'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/auth/update'
    | '/api/public/make-admin'
    | '/api/public/whatsapp-webhook'
    | '/api/storage/file'
    | '/api/storage/remove'
    | '/api/storage/upload'
    | '/_app/campaigns/'
    | '/api/public/contacts/ingest'
    | '/api/public/cron/process-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiAdminSchemaDumpRoute: typeof ApiAdminSchemaDumpRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthUpdateRoute: typeof ApiAuthUpdateRoute
  ApiPublicMakeAdminRoute: typeof ApiPublicMakeAdminRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiStorageRemoveRoute: typeof ApiStorageRemoveRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiPublicContactsIngestRoute: typeof ApiPublicContactsIngestRoute
  ApiPublicCronProcessQueueRoute: typeof ApiPublicCronProcessQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhook-events': {
      id: '/_app/webhook-events'
      path: '/webhook-events'
      fullPath: '/webhook-events'
      preLoaderRoute: typeof AppWebhookEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/remove': {
      id: '/api/storage/remove'
      path: '/api/storage/remove'
      fullPath: '/api/storage/remove'
      preLoaderRoute: typeof ApiStorageRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/make-admin': {
      id: '/api/public/make-admin'
      path: '/api/public/make-admin'
      fullPath: '/api/public/make-admin'
      preLoaderRoute: typeof ApiPublicMakeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/update': {
      id: '/api/auth/update'
      path: '/api/auth/update'
      fullPath: '/api/auth/update'
      preLoaderRoute: typeof ApiAuthUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/schema-dump': {
      id: '/api/admin/schema-dump'
      path: '/api/admin/schema-dump'
      fullPath: '/api/admin/schema-dump'
      preLoaderRoute: typeof ApiAdminSchemaDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cron/process-queue': {
      id: '/api/public/cron/process-queue'
      path: '/api/public/cron/process-queue'
      fullPath: '/api/public/cron/process-queue'
      preLoaderRoute: typeof ApiPublicCronProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts/ingest': {
      id: '/api/public/contacts/ingest'
      path: '/api/public/contacts/ingest'
      fullPath: '/api/public/contacts/ingest'
      preLoaderRoute: typeof ApiPublicContactsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppChatRoute: typeof AppChatRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppListsRoute: typeof AppListsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWebhookEventsRoute: typeof AppWebhookEventsRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppChatRoute: AppChatRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppListsRoute: AppListsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWebhookEventsRoute: AppWebhookEventsRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiAdminSchemaDumpRoute: ApiAdminSchemaDumpRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthUpdateRoute: ApiAuthUpdateRoute,
  ApiPublicMakeAdminRoute: ApiPublicMakeAdminRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiStorageRemoveRoute: ApiStorageRemoveRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiPublicContactsIngestRoute: ApiPublicContactsIngestRoute,
  ApiPublicCronProcessQueueRoute: ApiPublicCronProcessQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
