/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as AppWhatsappBusinessProfileRouteImport } from './routes/_app/whatsapp-business-profile'
import { Route as AppWebhooksRouteImport } from './routes/_app/webhooks'
import { Route as AppWebhookEventsRouteImport } from './routes/_app/webhook-events'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppListsRouteImport } from './routes/_app/lists'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBotRouteImport } from './routes/_app/bot'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAiAgentRouteImport } from './routes/_app/ai-agent'
import { Route as AppLicensesIndexRouteImport } from './routes/_app/licenses/index'
import { Route as AppDsAgenteIndexRouteImport } from './routes/_app/ds-agente/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app/campaigns.index'
import { Route as FunctionsV1MercadopagoWebhookRouteImport } from './routes/functions/v1/mercadopago-webhook'
import { Route as ApiWhatsappRegisterRouteImport } from './routes/api/whatsapp/register'
import { Route as ApiWhatsappMediaUploadRouteImport } from './routes/api/whatsapp/media-upload'
import { Route as ApiWhatsappMediaRouteImport } from './routes/api/whatsapp/media'
import { Route as ApiWhatsappGroupsRouteImport } from './routes/api/whatsapp/groups'
import { Route as ApiWhatsappBusinessProfileRouteImport } from './routes/api/whatsapp/business-profile'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as ApiWebhooksAsaasRouteImport } from './routes/api/webhooks/asaas'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageRemoveRouteImport } from './routes/api/storage/remove'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiSitemapXmlRouteImport } from './routes/api/sitemap.xml'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicInstagramWebhookRouteImport } from './routes/api/public/instagram-webhook'
import { Route as ApiPublicFacebookWebhookRouteImport } from './routes/api/public/facebook-webhook'
import { Route as ApiLicensesHealthRouteImport } from './routes/api/licenses/health'
import { Route as ApiBillingSubscriptionRouteImport } from './routes/api/billing/subscription'
import { Route as ApiBillingPublicKeyRouteImport } from './routes/api/billing/public-key'
import { Route as ApiBillingPlansRouteImport } from './routes/api/billing/plans'
import { Route as ApiBillingInvoicesRouteImport } from './routes/api/billing/invoices'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthVerifyTokenRouteImport } from './routes/api/auth/verify-token'
import { Route as ApiAuthUpdateRouteImport } from './routes/api/auth/update'
import { Route as ApiAuthTempPromoteRouteImport } from './routes/api/auth/temp-promote'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthOtpRouteImport } from './routes/api/auth/otp'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAdminTestSubscriptionsRunnerRouteImport } from './routes/api/admin/test-subscriptions-runner'
import { Route as ApiAdminSchemaMigrationRouteImport } from './routes/api/admin/schema-migration'
import { Route as ApiAdminSchemaDumpRouteImport } from './routes/api/admin/schema-dump'
import { Route as ApiAdminKillIdleConnectionsRouteImport } from './routes/api/admin/kill-idle-connections'
import { Route as ApiAdminFixSubscriptionsTableRouteImport } from './routes/api/admin/fix-subscriptions-table'
import { Route as AppSettingsCustomFieldsRouteImport } from './routes/_app/settings/custom-fields'
import { Route as AppLicensesIdRouteImport } from './routes/_app/licenses/$id'
import { Route as AppDsAgenteAgentIdRouteImport } from './routes/_app/ds-agente/$agentId'
import { Route as AppContactsIdRouteImport } from './routes/_app/contacts.$id'
import { Route as AppCampaignsIdRouteImport } from './routes/_app/campaigns.$id'
import { Route as ApiWhatsappBusinessProfilePhotoRouteImport } from './routes/api/whatsapp/business-profile.photo'
import { Route as ApiPublicCronProcessSubscriptionsRouteImport } from './routes/api/public/cron/process-subscriptions'
import { Route as ApiPublicCronProcessQueueRouteImport } from './routes/api/public/cron/process-queue'
import { Route as ApiPublicContactsIngestRouteImport } from './routes/api/public/contacts/ingest'
import { Route as ApiBillingSubscriptionRenewRouteImport } from './routes/api/billing/subscription/renew'
import { Route as ApiBillingInvoicesIdRouteImport } from './routes/api/billing/invoices/$id'
import { Route as ApiBillingCheckoutPixRouteImport } from './routes/api/billing/checkout/pix'
import { Route as ApiBillingCheckoutCardRouteImport } from './routes/api/billing/checkout/card'
import { Route as ApiAdminPaymentGatewaysMercadopagoRouteImport } from './routes/api/admin/payment-gateways/mercadopago'
import { Route as ApiPublicWebhooksIncomingTokenRouteImport } from './routes/api/public/webhooks/incoming/$token'
import { Route as ApiBillingPaymentsIdStatusRouteImport } from './routes/api/billing/payments/$id/status'
import { Route as ApiAdminPaymentGatewaysMercadopagoTestRouteImport } from './routes/api/admin/payment-gateways/mercadopago/test'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappBusinessProfileRoute =
  AppWhatsappBusinessProfileRouteImport.update({
    id: '/whatsapp-business-profile',
    path: '/whatsapp-business-profile',
    getParentRoute: () => AppRoute,
  } as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhookEventsRoute = AppWebhookEventsRouteImport.update({
  id: '/webhook-events',
  path: '/webhook-events',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBotRoute = AppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAgentRoute = AppAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => AppRoute,
} as any)
const AppLicensesIndexRoute = AppLicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppDsAgenteIndexRoute = AppDsAgenteIndexRouteImport.update({
  id: '/ds-agente/',
  path: '/ds-agente/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const FunctionsV1MercadopagoWebhookRoute =
  FunctionsV1MercadopagoWebhookRouteImport.update({
    id: '/functions/v1/mercadopago-webhook',
    path: '/functions/v1/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhatsappRegisterRoute = ApiWhatsappRegisterRouteImport.update({
  id: '/api/whatsapp/register',
  path: '/api/whatsapp/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappMediaUploadRoute = ApiWhatsappMediaUploadRouteImport.update({
  id: '/api/whatsapp/media-upload',
  path: '/api/whatsapp/media-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappMediaRoute = ApiWhatsappMediaRouteImport.update({
  id: '/api/whatsapp/media',
  path: '/api/whatsapp/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappGroupsRoute = ApiWhatsappGroupsRouteImport.update({
  id: '/api/whatsapp/groups',
  path: '/api/whatsapp/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappBusinessProfileRoute =
  ApiWhatsappBusinessProfileRouteImport.update({
    id: '/api/whatsapp/business-profile',
    path: '/api/whatsapp/business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAsaasRoute = ApiWebhooksAsaasRouteImport.update({
  id: '/api/webhooks/asaas',
  path: '/api/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRemoveRoute = ApiStorageRemoveRouteImport.update({
  id: '/api/storage/remove',
  path: '/api/storage/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapXmlRoute = ApiSitemapXmlRouteImport.update({
  id: '/api/sitemap/xml',
  path: '/api/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramWebhookRoute =
  ApiPublicInstagramWebhookRouteImport.update({
    id: '/api/public/instagram-webhook',
    path: '/api/public/instagram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFacebookWebhookRoute =
  ApiPublicFacebookWebhookRouteImport.update({
    id: '/api/public/facebook-webhook',
    path: '/api/public/facebook-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLicensesHealthRoute = ApiLicensesHealthRouteImport.update({
  id: '/api/licenses/health',
  path: '/api/licenses/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSubscriptionRoute = ApiBillingSubscriptionRouteImport.update({
  id: '/api/billing/subscription',
  path: '/api/billing/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPublicKeyRoute = ApiBillingPublicKeyRouteImport.update({
  id: '/api/billing/public-key',
  path: '/api/billing/public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlansRoute = ApiBillingPlansRouteImport.update({
  id: '/api/billing/plans',
  path: '/api/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoicesRoute = ApiBillingInvoicesRouteImport.update({
  id: '/api/billing/invoices',
  path: '/api/billing/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyTokenRoute = ApiAuthVerifyTokenRouteImport.update({
  id: '/api/auth/verify-token',
  path: '/api/auth/verify-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpdateRoute = ApiAuthUpdateRouteImport.update({
  id: '/api/auth/update',
  path: '/api/auth/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTempPromoteRoute = ApiAuthTempPromoteRouteImport.update({
  id: '/api/auth/temp-promote',
  path: '/api/auth/temp-promote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOtpRoute = ApiAuthOtpRouteImport.update({
  id: '/api/auth/otp',
  path: '/api/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestSubscriptionsRunnerRoute =
  ApiAdminTestSubscriptionsRunnerRouteImport.update({
    id: '/api/admin/test-subscriptions-runner',
    path: '/api/admin/test-subscriptions-runner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSchemaMigrationRoute = ApiAdminSchemaMigrationRouteImport.update({
  id: '/api/admin/schema-migration',
  path: '/api/admin/schema-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSchemaDumpRoute = ApiAdminSchemaDumpRouteImport.update({
  id: '/api/admin/schema-dump',
  path: '/api/admin/schema-dump',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKillIdleConnectionsRoute =
  ApiAdminKillIdleConnectionsRouteImport.update({
    id: '/api/admin/kill-idle-connections',
    path: '/api/admin/kill-idle-connections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminFixSubscriptionsTableRoute =
  ApiAdminFixSubscriptionsTableRouteImport.update({
    id: '/api/admin/fix-subscriptions-table',
    path: '/api/admin/fix-subscriptions-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsCustomFieldsRoute = AppSettingsCustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLicensesIdRoute = AppLicensesIdRouteImport.update({
  id: '/licenses/$id',
  path: '/licenses/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDsAgenteAgentIdRoute = AppDsAgenteAgentIdRouteImport.update({
  id: '/ds-agente/$agentId',
  path: '/ds-agente/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiWhatsappBusinessProfilePhotoRoute =
  ApiWhatsappBusinessProfilePhotoRouteImport.update({
    id: '/photo',
    path: '/photo',
    getParentRoute: () => ApiWhatsappBusinessProfileRoute,
  } as any)
const ApiPublicCronProcessSubscriptionsRoute =
  ApiPublicCronProcessSubscriptionsRouteImport.update({
    id: '/api/public/cron/process-subscriptions',
    path: '/api/public/cron/process-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronProcessQueueRoute =
  ApiPublicCronProcessQueueRouteImport.update({
    id: '/api/public/cron/process-queue',
    path: '/api/public/cron/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactsIngestRoute = ApiPublicContactsIngestRouteImport.update({
  id: '/api/public/contacts/ingest',
  path: '/api/public/contacts/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSubscriptionRenewRoute =
  ApiBillingSubscriptionRenewRouteImport.update({
    id: '/renew',
    path: '/renew',
    getParentRoute: () => ApiBillingSubscriptionRoute,
  } as any)
const ApiBillingInvoicesIdRoute = ApiBillingInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBillingInvoicesRoute,
} as any)
const ApiBillingCheckoutPixRoute = ApiBillingCheckoutPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => ApiBillingCheckoutRoute,
} as any)
const ApiBillingCheckoutCardRoute = ApiBillingCheckoutCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ApiBillingCheckoutRoute,
} as any)
const ApiAdminPaymentGatewaysMercadopagoRoute =
  ApiAdminPaymentGatewaysMercadopagoRouteImport.update({
    id: '/api/admin/payment-gateways/mercadopago',
    path: '/api/admin/payment-gateways/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksIncomingTokenRoute =
  ApiPublicWebhooksIncomingTokenRouteImport.update({
    id: '/api/public/webhooks/incoming/$token',
    path: '/api/public/webhooks/incoming/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingPaymentsIdStatusRoute =
  ApiBillingPaymentsIdStatusRouteImport.update({
    id: '/api/billing/payments/$id/status',
    path: '/api/billing/payments/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPaymentGatewaysMercadopagoTestRoute =
  ApiAdminPaymentGatewaysMercadopagoTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => ApiAdminPaymentGatewaysMercadopagoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/ai-agent': typeof AppAiAgentRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/bot': typeof AppBotRoute
  '/chat': typeof AppChatRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/groups': typeof AppGroupsRoute
  '/lists': typeof AppListsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/webhook-events': typeof AppWebhookEventsRoute
  '/webhooks': typeof AppWebhooksRoute
  '/whatsapp-business-profile': typeof AppWhatsappBusinessProfileRoute
  '/api/query': typeof ApiQueryRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/ds-agente/$agentId': typeof AppDsAgenteAgentIdRoute
  '/licenses/$id': typeof AppLicensesIdRoute
  '/settings/custom-fields': typeof AppSettingsCustomFieldsRoute
  '/api/admin/fix-subscriptions-table': typeof ApiAdminFixSubscriptionsTableRoute
  '/api/admin/kill-idle-connections': typeof ApiAdminKillIdleConnectionsRoute
  '/api/admin/schema-dump': typeof ApiAdminSchemaDumpRoute
  '/api/admin/schema-migration': typeof ApiAdminSchemaMigrationRoute
  '/api/admin/test-subscriptions-runner': typeof ApiAdminTestSubscriptionsRunnerRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/otp': typeof ApiAuthOtpRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/temp-promote': typeof ApiAuthTempPromoteRoute
  '/api/auth/update': typeof ApiAuthUpdateRoute
  '/api/auth/verify-token': typeof ApiAuthVerifyTokenRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRouteWithChildren
  '/api/billing/invoices': typeof ApiBillingInvoicesRouteWithChildren
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/public-key': typeof ApiBillingPublicKeyRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRouteWithChildren
  '/api/licenses/health': typeof ApiLicensesHealthRoute
  '/api/public/facebook-webhook': typeof ApiPublicFacebookWebhookRoute
  '/api/public/instagram-webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/remove': typeof ApiStorageRemoveRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/whatsapp/business-profile': typeof ApiWhatsappBusinessProfileRouteWithChildren
  '/api/whatsapp/groups': typeof ApiWhatsappGroupsRoute
  '/api/whatsapp/media': typeof ApiWhatsappMediaRoute
  '/api/whatsapp/media-upload': typeof ApiWhatsappMediaUploadRoute
  '/api/whatsapp/register': typeof ApiWhatsappRegisterRoute
  '/functions/v1/mercadopago-webhook': typeof FunctionsV1MercadopagoWebhookRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/ds-agente/': typeof AppDsAgenteIndexRoute
  '/licenses/': typeof AppLicensesIndexRoute
  '/api/admin/payment-gateways/mercadopago': typeof ApiAdminPaymentGatewaysMercadopagoRouteWithChildren
  '/api/billing/checkout/card': typeof ApiBillingCheckoutCardRoute
  '/api/billing/checkout/pix': typeof ApiBillingCheckoutPixRoute
  '/api/billing/invoices/$id': typeof ApiBillingInvoicesIdRoute
  '/api/billing/subscription/renew': typeof ApiBillingSubscriptionRenewRoute
  '/api/public/contacts/ingest': typeof ApiPublicContactsIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/cron/process-subscriptions': typeof ApiPublicCronProcessSubscriptionsRoute
  '/api/whatsapp/business-profile/photo': typeof ApiWhatsappBusinessProfilePhotoRoute
  '/api/admin/payment-gateways/mercadopago/test': typeof ApiAdminPaymentGatewaysMercadopagoTestRoute
  '/api/billing/payments/$id/status': typeof ApiBillingPaymentsIdStatusRoute
  '/api/public/webhooks/incoming/$token': typeof ApiPublicWebhooksIncomingTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/ai-agent': typeof AppAiAgentRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/bot': typeof AppBotRoute
  '/chat': typeof AppChatRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/groups': typeof AppGroupsRoute
  '/lists': typeof AppListsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/webhook-events': typeof AppWebhookEventsRoute
  '/webhooks': typeof AppWebhooksRoute
  '/whatsapp-business-profile': typeof AppWhatsappBusinessProfileRoute
  '/api/query': typeof ApiQueryRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/ds-agente/$agentId': typeof AppDsAgenteAgentIdRoute
  '/licenses/$id': typeof AppLicensesIdRoute
  '/settings/custom-fields': typeof AppSettingsCustomFieldsRoute
  '/api/admin/fix-subscriptions-table': typeof ApiAdminFixSubscriptionsTableRoute
  '/api/admin/kill-idle-connections': typeof ApiAdminKillIdleConnectionsRoute
  '/api/admin/schema-dump': typeof ApiAdminSchemaDumpRoute
  '/api/admin/schema-migration': typeof ApiAdminSchemaMigrationRoute
  '/api/admin/test-subscriptions-runner': typeof ApiAdminTestSubscriptionsRunnerRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/otp': typeof ApiAuthOtpRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/temp-promote': typeof ApiAuthTempPromoteRoute
  '/api/auth/update': typeof ApiAuthUpdateRoute
  '/api/auth/verify-token': typeof ApiAuthVerifyTokenRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRouteWithChildren
  '/api/billing/invoices': typeof ApiBillingInvoicesRouteWithChildren
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/public-key': typeof ApiBillingPublicKeyRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRouteWithChildren
  '/api/licenses/health': typeof ApiLicensesHealthRoute
  '/api/public/facebook-webhook': typeof ApiPublicFacebookWebhookRoute
  '/api/public/instagram-webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/remove': typeof ApiStorageRemoveRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/whatsapp/business-profile': typeof ApiWhatsappBusinessProfileRouteWithChildren
  '/api/whatsapp/groups': typeof ApiWhatsappGroupsRoute
  '/api/whatsapp/media': typeof ApiWhatsappMediaRoute
  '/api/whatsapp/media-upload': typeof ApiWhatsappMediaUploadRoute
  '/api/whatsapp/register': typeof ApiWhatsappRegisterRoute
  '/functions/v1/mercadopago-webhook': typeof FunctionsV1MercadopagoWebhookRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/ds-agente': typeof AppDsAgenteIndexRoute
  '/licenses': typeof AppLicensesIndexRoute
  '/api/admin/payment-gateways/mercadopago': typeof ApiAdminPaymentGatewaysMercadopagoRouteWithChildren
  '/api/billing/checkout/card': typeof ApiBillingCheckoutCardRoute
  '/api/billing/checkout/pix': typeof ApiBillingCheckoutPixRoute
  '/api/billing/invoices/$id': typeof ApiBillingInvoicesIdRoute
  '/api/billing/subscription/renew': typeof ApiBillingSubscriptionRenewRoute
  '/api/public/contacts/ingest': typeof ApiPublicContactsIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/cron/process-subscriptions': typeof ApiPublicCronProcessSubscriptionsRoute
  '/api/whatsapp/business-profile/photo': typeof ApiWhatsappBusinessProfilePhotoRoute
  '/api/admin/payment-gateways/mercadopago/test': typeof ApiAdminPaymentGatewaysMercadopagoTestRoute
  '/api/billing/payments/$id/status': typeof ApiBillingPaymentsIdStatusRoute
  '/api/public/webhooks/incoming/$token': typeof ApiPublicWebhooksIncomingTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_app/ai-agent': typeof AppAiAgentRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/bot': typeof AppBotRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/lists': typeof AppListsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/webhook-events': typeof AppWebhookEventsRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/_app/whatsapp-business-profile': typeof AppWhatsappBusinessProfileRoute
  '/api/query': typeof ApiQueryRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/ds-agente/$agentId': typeof AppDsAgenteAgentIdRoute
  '/_app/licenses/$id': typeof AppLicensesIdRoute
  '/_app/settings/custom-fields': typeof AppSettingsCustomFieldsRoute
  '/api/admin/fix-subscriptions-table': typeof ApiAdminFixSubscriptionsTableRoute
  '/api/admin/kill-idle-connections': typeof ApiAdminKillIdleConnectionsRoute
  '/api/admin/schema-dump': typeof ApiAdminSchemaDumpRoute
  '/api/admin/schema-migration': typeof ApiAdminSchemaMigrationRoute
  '/api/admin/test-subscriptions-runner': typeof ApiAdminTestSubscriptionsRunnerRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/otp': typeof ApiAuthOtpRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/temp-promote': typeof ApiAuthTempPromoteRoute
  '/api/auth/update': typeof ApiAuthUpdateRoute
  '/api/auth/verify-token': typeof ApiAuthVerifyTokenRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRouteWithChildren
  '/api/billing/invoices': typeof ApiBillingInvoicesRouteWithChildren
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/public-key': typeof ApiBillingPublicKeyRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRouteWithChildren
  '/api/licenses/health': typeof ApiLicensesHealthRoute
  '/api/public/facebook-webhook': typeof ApiPublicFacebookWebhookRoute
  '/api/public/instagram-webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/remove': typeof ApiStorageRemoveRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/whatsapp/business-profile': typeof ApiWhatsappBusinessProfileRouteWithChildren
  '/api/whatsapp/groups': typeof ApiWhatsappGroupsRoute
  '/api/whatsapp/media': typeof ApiWhatsappMediaRoute
  '/api/whatsapp/media-upload': typeof ApiWhatsappMediaUploadRoute
  '/api/whatsapp/register': typeof ApiWhatsappRegisterRoute
  '/functions/v1/mercadopago-webhook': typeof FunctionsV1MercadopagoWebhookRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/ds-agente/': typeof AppDsAgenteIndexRoute
  '/_app/licenses/': typeof AppLicensesIndexRoute
  '/api/admin/payment-gateways/mercadopago': typeof ApiAdminPaymentGatewaysMercadopagoRouteWithChildren
  '/api/billing/checkout/card': typeof ApiBillingCheckoutCardRoute
  '/api/billing/checkout/pix': typeof ApiBillingCheckoutPixRoute
  '/api/billing/invoices/$id': typeof ApiBillingInvoicesIdRoute
  '/api/billing/subscription/renew': typeof ApiBillingSubscriptionRenewRoute
  '/api/public/contacts/ingest': typeof ApiPublicContactsIngestRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/cron/process-subscriptions': typeof ApiPublicCronProcessSubscriptionsRoute
  '/api/whatsapp/business-profile/photo': typeof ApiWhatsappBusinessProfilePhotoRoute
  '/api/admin/payment-gateways/mercadopago/test': typeof ApiAdminPaymentGatewaysMercadopagoTestRoute
  '/api/billing/payments/$id/status': typeof ApiBillingPaymentsIdStatusRoute
  '/api/public/webhooks/incoming/$token': typeof ApiPublicWebhooksIncomingTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/ai-agent'
    | '/audit'
    | '/billing'
    | '/bot'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/docs'
    | '/groups'
    | '/lists'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/users'
    | '/webhook-events'
    | '/webhooks'
    | '/whatsapp-business-profile'
    | '/api/query'
    | '/campaigns/$id'
    | '/contacts/$id'
    | '/ds-agente/$agentId'
    | '/licenses/$id'
    | '/settings/custom-fields'
    | '/api/admin/fix-subscriptions-table'
    | '/api/admin/kill-idle-connections'
    | '/api/admin/schema-dump'
    | '/api/admin/schema-migration'
    | '/api/admin/test-subscriptions-runner'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/otp'
    | '/api/auth/register'
    | '/api/auth/temp-promote'
    | '/api/auth/update'
    | '/api/auth/verify-token'
    | '/api/billing/checkout'
    | '/api/billing/invoices'
    | '/api/billing/plans'
    | '/api/billing/public-key'
    | '/api/billing/subscription'
    | '/api/licenses/health'
    | '/api/public/facebook-webhook'
    | '/api/public/instagram-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/sitemap/xml'
    | '/api/storage/file'
    | '/api/storage/remove'
    | '/api/storage/upload'
    | '/api/webhooks/asaas'
    | '/api/webhooks/mercadopago'
    | '/api/whatsapp/business-profile'
    | '/api/whatsapp/groups'
    | '/api/whatsapp/media'
    | '/api/whatsapp/media-upload'
    | '/api/whatsapp/register'
    | '/functions/v1/mercadopago-webhook'
    | '/campaigns/'
    | '/contacts/'
    | '/ds-agente/'
    | '/licenses/'
    | '/api/admin/payment-gateways/mercadopago'
    | '/api/billing/checkout/card'
    | '/api/billing/checkout/pix'
    | '/api/billing/invoices/$id'
    | '/api/billing/subscription/renew'
    | '/api/public/contacts/ingest'
    | '/api/public/cron/process-queue'
    | '/api/public/cron/process-subscriptions'
    | '/api/whatsapp/business-profile/photo'
    | '/api/admin/payment-gateways/mercadopago/test'
    | '/api/billing/payments/$id/status'
    | '/api/public/webhooks/incoming/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/ai-agent'
    | '/audit'
    | '/billing'
    | '/bot'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/docs'
    | '/groups'
    | '/lists'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/users'
    | '/webhook-events'
    | '/webhooks'
    | '/whatsapp-business-profile'
    | '/api/query'
    | '/campaigns/$id'
    | '/contacts/$id'
    | '/ds-agente/$agentId'
    | '/licenses/$id'
    | '/settings/custom-fields'
    | '/api/admin/fix-subscriptions-table'
    | '/api/admin/kill-idle-connections'
    | '/api/admin/schema-dump'
    | '/api/admin/schema-migration'
    | '/api/admin/test-subscriptions-runner'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/otp'
    | '/api/auth/register'
    | '/api/auth/temp-promote'
    | '/api/auth/update'
    | '/api/auth/verify-token'
    | '/api/billing/checkout'
    | '/api/billing/invoices'
    | '/api/billing/plans'
    | '/api/billing/public-key'
    | '/api/billing/subscription'
    | '/api/licenses/health'
    | '/api/public/facebook-webhook'
    | '/api/public/instagram-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/sitemap/xml'
    | '/api/storage/file'
    | '/api/storage/remove'
    | '/api/storage/upload'
    | '/api/webhooks/asaas'
    | '/api/webhooks/mercadopago'
    | '/api/whatsapp/business-profile'
    | '/api/whatsapp/groups'
    | '/api/whatsapp/media'
    | '/api/whatsapp/media-upload'
    | '/api/whatsapp/register'
    | '/functions/v1/mercadopago-webhook'
    | '/campaigns'
    | '/contacts'
    | '/ds-agente'
    | '/licenses'
    | '/api/admin/payment-gateways/mercadopago'
    | '/api/billing/checkout/card'
    | '/api/billing/checkout/pix'
    | '/api/billing/invoices/$id'
    | '/api/billing/subscription/renew'
    | '/api/public/contacts/ingest'
    | '/api/public/cron/process-queue'
    | '/api/public/cron/process-subscriptions'
    | '/api/whatsapp/business-profile/photo'
    | '/api/admin/payment-gateways/mercadopago/test'
    | '/api/billing/payments/$id/status'
    | '/api/public/webhooks/incoming/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_app/ai-agent'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/bot'
    | '/_app/chat'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/docs'
    | '/_app/groups'
    | '/_app/lists'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/users'
    | '/_app/webhook-events'
    | '/_app/webhooks'
    | '/_app/whatsapp-business-profile'
    | '/api/query'
    | '/_app/campaigns/$id'
    | '/_app/contacts/$id'
    | '/_app/ds-agente/$agentId'
    | '/_app/licenses/$id'
    | '/_app/settings/custom-fields'
    | '/api/admin/fix-subscriptions-table'
    | '/api/admin/kill-idle-connections'
    | '/api/admin/schema-dump'
    | '/api/admin/schema-migration'
    | '/api/admin/test-subscriptions-runner'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/otp'
    | '/api/auth/register'
    | '/api/auth/temp-promote'
    | '/api/auth/update'
    | '/api/auth/verify-token'
    | '/api/billing/checkout'
    | '/api/billing/invoices'
    | '/api/billing/plans'
    | '/api/billing/public-key'
    | '/api/billing/subscription'
    | '/api/licenses/health'
    | '/api/public/facebook-webhook'
    | '/api/public/instagram-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/sitemap/xml'
    | '/api/storage/file'
    | '/api/storage/remove'
    | '/api/storage/upload'
    | '/api/webhooks/asaas'
    | '/api/webhooks/mercadopago'
    | '/api/whatsapp/business-profile'
    | '/api/whatsapp/groups'
    | '/api/whatsapp/media'
    | '/api/whatsapp/media-upload'
    | '/api/whatsapp/register'
    | '/functions/v1/mercadopago-webhook'
    | '/_app/campaigns/'
    | '/_app/contacts/'
    | '/_app/ds-agente/'
    | '/_app/licenses/'
    | '/api/admin/payment-gateways/mercadopago'
    | '/api/billing/checkout/card'
    | '/api/billing/checkout/pix'
    | '/api/billing/invoices/$id'
    | '/api/billing/subscription/renew'
    | '/api/public/contacts/ingest'
    | '/api/public/cron/process-queue'
    | '/api/public/cron/process-subscriptions'
    | '/api/whatsapp/business-profile/photo'
    | '/api/admin/payment-gateways/mercadopago/test'
    | '/api/billing/payments/$id/status'
    | '/api/public/webhooks/incoming/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiAdminFixSubscriptionsTableRoute: typeof ApiAdminFixSubscriptionsTableRoute
  ApiAdminKillIdleConnectionsRoute: typeof ApiAdminKillIdleConnectionsRoute
  ApiAdminSchemaDumpRoute: typeof ApiAdminSchemaDumpRoute
  ApiAdminSchemaMigrationRoute: typeof ApiAdminSchemaMigrationRoute
  ApiAdminTestSubscriptionsRunnerRoute: typeof ApiAdminTestSubscriptionsRunnerRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthOtpRoute: typeof ApiAuthOtpRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthTempPromoteRoute: typeof ApiAuthTempPromoteRoute
  ApiAuthUpdateRoute: typeof ApiAuthUpdateRoute
  ApiAuthVerifyTokenRoute: typeof ApiAuthVerifyTokenRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRouteWithChildren
  ApiBillingInvoicesRoute: typeof ApiBillingInvoicesRouteWithChildren
  ApiBillingPlansRoute: typeof ApiBillingPlansRoute
  ApiBillingPublicKeyRoute: typeof ApiBillingPublicKeyRoute
  ApiBillingSubscriptionRoute: typeof ApiBillingSubscriptionRouteWithChildren
  ApiLicensesHealthRoute: typeof ApiLicensesHealthRoute
  ApiPublicFacebookWebhookRoute: typeof ApiPublicFacebookWebhookRoute
  ApiPublicInstagramWebhookRoute: typeof ApiPublicInstagramWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiSitemapXmlRoute: typeof ApiSitemapXmlRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiStorageRemoveRoute: typeof ApiStorageRemoveRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiWebhooksAsaasRoute: typeof ApiWebhooksAsaasRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
  ApiWhatsappBusinessProfileRoute: typeof ApiWhatsappBusinessProfileRouteWithChildren
  ApiWhatsappGroupsRoute: typeof ApiWhatsappGroupsRoute
  ApiWhatsappMediaRoute: typeof ApiWhatsappMediaRoute
  ApiWhatsappMediaUploadRoute: typeof ApiWhatsappMediaUploadRoute
  ApiWhatsappRegisterRoute: typeof ApiWhatsappRegisterRoute
  FunctionsV1MercadopagoWebhookRoute: typeof FunctionsV1MercadopagoWebhookRoute
  ApiAdminPaymentGatewaysMercadopagoRoute: typeof ApiAdminPaymentGatewaysMercadopagoRouteWithChildren
  ApiPublicContactsIngestRoute: typeof ApiPublicContactsIngestRoute
  ApiPublicCronProcessQueueRoute: typeof ApiPublicCronProcessQueueRoute
  ApiPublicCronProcessSubscriptionsRoute: typeof ApiPublicCronProcessSubscriptionsRoute
  ApiBillingPaymentsIdStatusRoute: typeof ApiBillingPaymentsIdStatusRoute
  ApiPublicWebhooksIncomingTokenRoute: typeof ApiPublicWebhooksIncomingTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp-business-profile': {
      id: '/_app/whatsapp-business-profile'
      path: '/whatsapp-business-profile'
      fullPath: '/whatsapp-business-profile'
      preLoaderRoute: typeof AppWhatsappBusinessProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhook-events': {
      id: '/_app/webhook-events'
      path: '/webhook-events'
      fullPath: '/webhook-events'
      preLoaderRoute: typeof AppWebhookEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bot': {
      id: '/_app/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AppBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agent': {
      id: '/_app/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AppAiAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licenses/': {
      id: '/_app/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof AppLicensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ds-agente/': {
      id: '/_app/ds-agente/'
      path: '/ds-agente'
      fullPath: '/ds-agente/'
      preLoaderRoute: typeof AppDsAgenteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/functions/v1/mercadopago-webhook': {
      id: '/functions/v1/mercadopago-webhook'
      path: '/functions/v1/mercadopago-webhook'
      fullPath: '/functions/v1/mercadopago-webhook'
      preLoaderRoute: typeof FunctionsV1MercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/register': {
      id: '/api/whatsapp/register'
      path: '/api/whatsapp/register'
      fullPath: '/api/whatsapp/register'
      preLoaderRoute: typeof ApiWhatsappRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/media-upload': {
      id: '/api/whatsapp/media-upload'
      path: '/api/whatsapp/media-upload'
      fullPath: '/api/whatsapp/media-upload'
      preLoaderRoute: typeof ApiWhatsappMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/media': {
      id: '/api/whatsapp/media'
      path: '/api/whatsapp/media'
      fullPath: '/api/whatsapp/media'
      preLoaderRoute: typeof ApiWhatsappMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/groups': {
      id: '/api/whatsapp/groups'
      path: '/api/whatsapp/groups'
      fullPath: '/api/whatsapp/groups'
      preLoaderRoute: typeof ApiWhatsappGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/business-profile': {
      id: '/api/whatsapp/business-profile'
      path: '/api/whatsapp/business-profile'
      fullPath: '/api/whatsapp/business-profile'
      preLoaderRoute: typeof ApiWhatsappBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/asaas': {
      id: '/api/webhooks/asaas'
      path: '/api/webhooks/asaas'
      fullPath: '/api/webhooks/asaas'
      preLoaderRoute: typeof ApiWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/remove': {
      id: '/api/storage/remove'
      path: '/api/storage/remove'
      fullPath: '/api/storage/remove'
      preLoaderRoute: typeof ApiStorageRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/xml': {
      id: '/api/sitemap/xml'
      path: '/api/sitemap/xml'
      fullPath: '/api/sitemap/xml'
      preLoaderRoute: typeof ApiSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-webhook': {
      id: '/api/public/instagram-webhook'
      path: '/api/public/instagram-webhook'
      fullPath: '/api/public/instagram-webhook'
      preLoaderRoute: typeof ApiPublicInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/facebook-webhook': {
      id: '/api/public/facebook-webhook'
      path: '/api/public/facebook-webhook'
      fullPath: '/api/public/facebook-webhook'
      preLoaderRoute: typeof ApiPublicFacebookWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/licenses/health': {
      id: '/api/licenses/health'
      path: '/api/licenses/health'
      fullPath: '/api/licenses/health'
      preLoaderRoute: typeof ApiLicensesHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscription': {
      id: '/api/billing/subscription'
      path: '/api/billing/subscription'
      fullPath: '/api/billing/subscription'
      preLoaderRoute: typeof ApiBillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/public-key': {
      id: '/api/billing/public-key'
      path: '/api/billing/public-key'
      fullPath: '/api/billing/public-key'
      preLoaderRoute: typeof ApiBillingPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plans': {
      id: '/api/billing/plans'
      path: '/api/billing/plans'
      fullPath: '/api/billing/plans'
      preLoaderRoute: typeof ApiBillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoices': {
      id: '/api/billing/invoices'
      path: '/api/billing/invoices'
      fullPath: '/api/billing/invoices'
      preLoaderRoute: typeof ApiBillingInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-token': {
      id: '/api/auth/verify-token'
      path: '/api/auth/verify-token'
      fullPath: '/api/auth/verify-token'
      preLoaderRoute: typeof ApiAuthVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/update': {
      id: '/api/auth/update'
      path: '/api/auth/update'
      fullPath: '/api/auth/update'
      preLoaderRoute: typeof ApiAuthUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/temp-promote': {
      id: '/api/auth/temp-promote'
      path: '/api/auth/temp-promote'
      fullPath: '/api/auth/temp-promote'
      preLoaderRoute: typeof ApiAuthTempPromoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/otp': {
      id: '/api/auth/otp'
      path: '/api/auth/otp'
      fullPath: '/api/auth/otp'
      preLoaderRoute: typeof ApiAuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-subscriptions-runner': {
      id: '/api/admin/test-subscriptions-runner'
      path: '/api/admin/test-subscriptions-runner'
      fullPath: '/api/admin/test-subscriptions-runner'
      preLoaderRoute: typeof ApiAdminTestSubscriptionsRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/schema-migration': {
      id: '/api/admin/schema-migration'
      path: '/api/admin/schema-migration'
      fullPath: '/api/admin/schema-migration'
      preLoaderRoute: typeof ApiAdminSchemaMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/schema-dump': {
      id: '/api/admin/schema-dump'
      path: '/api/admin/schema-dump'
      fullPath: '/api/admin/schema-dump'
      preLoaderRoute: typeof ApiAdminSchemaDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/kill-idle-connections': {
      id: '/api/admin/kill-idle-connections'
      path: '/api/admin/kill-idle-connections'
      fullPath: '/api/admin/kill-idle-connections'
      preLoaderRoute: typeof ApiAdminKillIdleConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fix-subscriptions-table': {
      id: '/api/admin/fix-subscriptions-table'
      path: '/api/admin/fix-subscriptions-table'
      fullPath: '/api/admin/fix-subscriptions-table'
      preLoaderRoute: typeof ApiAdminFixSubscriptionsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/custom-fields': {
      id: '/_app/settings/custom-fields'
      path: '/custom-fields'
      fullPath: '/settings/custom-fields'
      preLoaderRoute: typeof AppSettingsCustomFieldsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/licenses/$id': {
      id: '/_app/licenses/$id'
      path: '/licenses/$id'
      fullPath: '/licenses/$id'
      preLoaderRoute: typeof AppLicensesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ds-agente/$agentId': {
      id: '/_app/ds-agente/$agentId'
      path: '/ds-agente/$agentId'
      fullPath: '/ds-agente/$agentId'
      preLoaderRoute: typeof AppDsAgenteAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/whatsapp/business-profile/photo': {
      id: '/api/whatsapp/business-profile/photo'
      path: '/photo'
      fullPath: '/api/whatsapp/business-profile/photo'
      preLoaderRoute: typeof ApiWhatsappBusinessProfilePhotoRouteImport
      parentRoute: typeof ApiWhatsappBusinessProfileRoute
    }
    '/api/public/cron/process-subscriptions': {
      id: '/api/public/cron/process-subscriptions'
      path: '/api/public/cron/process-subscriptions'
      fullPath: '/api/public/cron/process-subscriptions'
      preLoaderRoute: typeof ApiPublicCronProcessSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-queue': {
      id: '/api/public/cron/process-queue'
      path: '/api/public/cron/process-queue'
      fullPath: '/api/public/cron/process-queue'
      preLoaderRoute: typeof ApiPublicCronProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts/ingest': {
      id: '/api/public/contacts/ingest'
      path: '/api/public/contacts/ingest'
      fullPath: '/api/public/contacts/ingest'
      preLoaderRoute: typeof ApiPublicContactsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscription/renew': {
      id: '/api/billing/subscription/renew'
      path: '/renew'
      fullPath: '/api/billing/subscription/renew'
      preLoaderRoute: typeof ApiBillingSubscriptionRenewRouteImport
      parentRoute: typeof ApiBillingSubscriptionRoute
    }
    '/api/billing/invoices/$id': {
      id: '/api/billing/invoices/$id'
      path: '/$id'
      fullPath: '/api/billing/invoices/$id'
      preLoaderRoute: typeof ApiBillingInvoicesIdRouteImport
      parentRoute: typeof ApiBillingInvoicesRoute
    }
    '/api/billing/checkout/pix': {
      id: '/api/billing/checkout/pix'
      path: '/pix'
      fullPath: '/api/billing/checkout/pix'
      preLoaderRoute: typeof ApiBillingCheckoutPixRouteImport
      parentRoute: typeof ApiBillingCheckoutRoute
    }
    '/api/billing/checkout/card': {
      id: '/api/billing/checkout/card'
      path: '/card'
      fullPath: '/api/billing/checkout/card'
      preLoaderRoute: typeof ApiBillingCheckoutCardRouteImport
      parentRoute: typeof ApiBillingCheckoutRoute
    }
    '/api/admin/payment-gateways/mercadopago': {
      id: '/api/admin/payment-gateways/mercadopago'
      path: '/api/admin/payment-gateways/mercadopago'
      fullPath: '/api/admin/payment-gateways/mercadopago'
      preLoaderRoute: typeof ApiAdminPaymentGatewaysMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/incoming/$token': {
      id: '/api/public/webhooks/incoming/$token'
      path: '/api/public/webhooks/incoming/$token'
      fullPath: '/api/public/webhooks/incoming/$token'
      preLoaderRoute: typeof ApiPublicWebhooksIncomingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/$id/status': {
      id: '/api/billing/payments/$id/status'
      path: '/api/billing/payments/$id/status'
      fullPath: '/api/billing/payments/$id/status'
      preLoaderRoute: typeof ApiBillingPaymentsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payment-gateways/mercadopago/test': {
      id: '/api/admin/payment-gateways/mercadopago/test'
      path: '/test'
      fullPath: '/api/admin/payment-gateways/mercadopago/test'
      preLoaderRoute: typeof ApiAdminPaymentGatewaysMercadopagoTestRouteImport
      parentRoute: typeof ApiAdminPaymentGatewaysMercadopagoRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsCustomFieldsRoute: typeof AppSettingsCustomFieldsRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsCustomFieldsRoute: AppSettingsCustomFieldsRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAiAgentRoute: typeof AppAiAgentRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBotRoute: typeof AppBotRoute
  AppChatRoute: typeof AppChatRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocsRoute: typeof AppDocsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppListsRoute: typeof AppListsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWebhookEventsRoute: typeof AppWebhookEventsRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppWhatsappBusinessProfileRoute: typeof AppWhatsappBusinessProfileRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppContactsIdRoute: typeof AppContactsIdRoute
  AppDsAgenteAgentIdRoute: typeof AppDsAgenteAgentIdRoute
  AppLicensesIdRoute: typeof AppLicensesIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppDsAgenteIndexRoute: typeof AppDsAgenteIndexRoute
  AppLicensesIndexRoute: typeof AppLicensesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAgentRoute: AppAiAgentRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppBotRoute: AppBotRoute,
  AppChatRoute: AppChatRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocsRoute: AppDocsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppListsRoute: AppListsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWebhookEventsRoute: AppWebhookEventsRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppWhatsappBusinessProfileRoute: AppWhatsappBusinessProfileRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppContactsIdRoute: AppContactsIdRoute,
  AppDsAgenteAgentIdRoute: AppDsAgenteAgentIdRoute,
  AppLicensesIdRoute: AppLicensesIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppDsAgenteIndexRoute: AppDsAgenteIndexRoute,
  AppLicensesIndexRoute: AppLicensesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiBillingCheckoutRouteChildren {
  ApiBillingCheckoutCardRoute: typeof ApiBillingCheckoutCardRoute
  ApiBillingCheckoutPixRoute: typeof ApiBillingCheckoutPixRoute
}

const ApiBillingCheckoutRouteChildren: ApiBillingCheckoutRouteChildren = {
  ApiBillingCheckoutCardRoute: ApiBillingCheckoutCardRoute,
  ApiBillingCheckoutPixRoute: ApiBillingCheckoutPixRoute,
}

const ApiBillingCheckoutRouteWithChildren =
  ApiBillingCheckoutRoute._addFileChildren(ApiBillingCheckoutRouteChildren)

interface ApiBillingInvoicesRouteChildren {
  ApiBillingInvoicesIdRoute: typeof ApiBillingInvoicesIdRoute
}

const ApiBillingInvoicesRouteChildren: ApiBillingInvoicesRouteChildren = {
  ApiBillingInvoicesIdRoute: ApiBillingInvoicesIdRoute,
}

const ApiBillingInvoicesRouteWithChildren =
  ApiBillingInvoicesRoute._addFileChildren(ApiBillingInvoicesRouteChildren)

interface ApiBillingSubscriptionRouteChildren {
  ApiBillingSubscriptionRenewRoute: typeof ApiBillingSubscriptionRenewRoute
}

const ApiBillingSubscriptionRouteChildren: ApiBillingSubscriptionRouteChildren =
  {
    ApiBillingSubscriptionRenewRoute: ApiBillingSubscriptionRenewRoute,
  }

const ApiBillingSubscriptionRouteWithChildren =
  ApiBillingSubscriptionRoute._addFileChildren(
    ApiBillingSubscriptionRouteChildren,
  )

interface ApiWhatsappBusinessProfileRouteChildren {
  ApiWhatsappBusinessProfilePhotoRoute: typeof ApiWhatsappBusinessProfilePhotoRoute
}

const ApiWhatsappBusinessProfileRouteChildren: ApiWhatsappBusinessProfileRouteChildren =
  {
    ApiWhatsappBusinessProfilePhotoRoute: ApiWhatsappBusinessProfilePhotoRoute,
  }

const ApiWhatsappBusinessProfileRouteWithChildren =
  ApiWhatsappBusinessProfileRoute._addFileChildren(
    ApiWhatsappBusinessProfileRouteChildren,
  )

interface ApiAdminPaymentGatewaysMercadopagoRouteChildren {
  ApiAdminPaymentGatewaysMercadopagoTestRoute: typeof ApiAdminPaymentGatewaysMercadopagoTestRoute
}

const ApiAdminPaymentGatewaysMercadopagoRouteChildren: ApiAdminPaymentGatewaysMercadopagoRouteChildren =
  {
    ApiAdminPaymentGatewaysMercadopagoTestRoute:
      ApiAdminPaymentGatewaysMercadopagoTestRoute,
  }

const ApiAdminPaymentGatewaysMercadopagoRouteWithChildren =
  ApiAdminPaymentGatewaysMercadopagoRoute._addFileChildren(
    ApiAdminPaymentGatewaysMercadopagoRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiAdminFixSubscriptionsTableRoute: ApiAdminFixSubscriptionsTableRoute,
  ApiAdminKillIdleConnectionsRoute: ApiAdminKillIdleConnectionsRoute,
  ApiAdminSchemaDumpRoute: ApiAdminSchemaDumpRoute,
  ApiAdminSchemaMigrationRoute: ApiAdminSchemaMigrationRoute,
  ApiAdminTestSubscriptionsRunnerRoute: ApiAdminTestSubscriptionsRunnerRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthOtpRoute: ApiAuthOtpRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthTempPromoteRoute: ApiAuthTempPromoteRoute,
  ApiAuthUpdateRoute: ApiAuthUpdateRoute,
  ApiAuthVerifyTokenRoute: ApiAuthVerifyTokenRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRouteWithChildren,
  ApiBillingInvoicesRoute: ApiBillingInvoicesRouteWithChildren,
  ApiBillingPlansRoute: ApiBillingPlansRoute,
  ApiBillingPublicKeyRoute: ApiBillingPublicKeyRoute,
  ApiBillingSubscriptionRoute: ApiBillingSubscriptionRouteWithChildren,
  ApiLicensesHealthRoute: ApiLicensesHealthRoute,
  ApiPublicFacebookWebhookRoute: ApiPublicFacebookWebhookRoute,
  ApiPublicInstagramWebhookRoute: ApiPublicInstagramWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiSitemapXmlRoute: ApiSitemapXmlRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiStorageRemoveRoute: ApiStorageRemoveRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiWebhooksAsaasRoute: ApiWebhooksAsaasRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
  ApiWhatsappBusinessProfileRoute: ApiWhatsappBusinessProfileRouteWithChildren,
  ApiWhatsappGroupsRoute: ApiWhatsappGroupsRoute,
  ApiWhatsappMediaRoute: ApiWhatsappMediaRoute,
  ApiWhatsappMediaUploadRoute: ApiWhatsappMediaUploadRoute,
  ApiWhatsappRegisterRoute: ApiWhatsappRegisterRoute,
  FunctionsV1MercadopagoWebhookRoute: FunctionsV1MercadopagoWebhookRoute,
  ApiAdminPaymentGatewaysMercadopagoRoute:
    ApiAdminPaymentGatewaysMercadopagoRouteWithChildren,
  ApiPublicContactsIngestRoute: ApiPublicContactsIngestRoute,
  ApiPublicCronProcessQueueRoute: ApiPublicCronProcessQueueRoute,
  ApiPublicCronProcessSubscriptionsRoute:
    ApiPublicCronProcessSubscriptionsRoute,
  ApiBillingPaymentsIdStatusRoute: ApiBillingPaymentsIdStatusRoute,
  ApiPublicWebhooksIncomingTokenRoute: ApiPublicWebhooksIncomingTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
